version: "3"
services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=ThermalCycle
      - INFLUXDB_USER=user
      - INFLUXDB_USR_PASSWORD=user
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    volumes:
      - ./influxdb/data:/var/lib/influxdb
      - ./influxdb/conf:/etc/influxdb

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    user: '472:0'
    volumes:
      - ./grafana/data:/var/lib/grafana
    depends_on:
      - influxdb
  python3:
    restart: always
    build: .
    container_name: 'python3'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./python:/root/opt
volumes:
  influxdb:
  grafana:
